NUM_ROW = 30
NUM_COL = 30
GAME_DIMENSIONS = (NUM_ROW, NUM_COL)

SNAKE_START = [(15,15),(16,15),(17,15)]

NUM_RUNS = 100
ALGORITHM_LIST = ["fixed"]

# Visualizer Settings
PX_PER_SQUARE = 20
VIS_HEIGHT = PX_PER_SQUARE * GAME_DIMENSIONS[0]
VIS_WIDTH  = PX_PER_SQUARE * GAME_DIMENSIONS[1]
VIS_TARGET_STEPS_PER_SECOND = 100
VIS_TARGET_STEP_TIME = 1 / VIS_TARGET_STEPS_PER_SECOND